SET DB_CLOSE_DELAY -1;        
;             
CREATE USER IF NOT EXISTS "SA" SALT '0cebf6c82b77c9ef' HASH '8f92d4a7f6bb920381ce35a21c0804237c78d62426719a594f1ec154bfd88a97' ADMIN;         
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_5F1507ED_2379_41D1_BBC5_8BB0C7B51F6C" START WITH 10 BELONGS_TO_TABLE;               
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_1496B911_6026_4315_9638_47A766720F5C" START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_1AE7C9AB_17F9_4B2D_9E4B_E3EAA1ACE345" START WITH 7 BELONGS_TO_TABLE;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_304EE047_2DF7_44F9_9D97_2ED60B175707" START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_64EC1097_EAD8_480E_A2D5_0176ABC70EA5" START WITH 3 BELONGS_TO_TABLE;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_078DFFAF_A379_4864_BBCB_0059FBF56407" START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_55F404D9_EDBC_4FE5_9E64_7068F7D4D5C8" START WITH 4 BELONGS_TO_TABLE;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_E3F24E08_F1B6_4696_85E6_2D479898F962" START WITH 2 BELONGS_TO_TABLE;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_05CF52E9_B704_4104_906E_AC11EF5E2F2E" START WITH 10 BELONGS_TO_TABLE;               
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_186BB2C9_03AA_4244_8F5C_A7EAFA5F07B6" START WITH 4 BELONGS_TO_TABLE;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_A7569051_2908_42EC_82FF_FFCF8B6C0C5C" START WITH 10 BELONGS_TO_TABLE;               
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_EAB85C26_B914_49E2_917A_854A20C60790" START WITH 2 BELONGS_TO_TABLE;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_7E9D1DA6_D37C_4D73_A55F_116C1EE146B9" START WITH 5 BELONGS_TO_TABLE;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_FB0288B7_72F7_4480_88F5_85A4AFADD146" START WITH 2 BELONGS_TO_TABLE;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_672244CE_9931_481F_806C_332D3C3C1AC7" START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_96519897_92BB_4F58_8416_2308B28154FB" START WITH 1 BELONGS_TO_TABLE;
CREATE MEMORY TABLE "PUBLIC"."ADDRESS"(
    "ID" BIGINT DEFAULT (NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_E3F24E08_F1B6_4696_85E6_2D479898F962") NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_E3F24E08_F1B6_4696_85E6_2D479898F962",
    "CITY" VARCHAR(255),
    "STATE" VARCHAR(255),
    "STREET" VARCHAR(255),
    "ZIP" VARCHAR(255)
);             
ALTER TABLE "PUBLIC"."ADDRESS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_E" PRIMARY KEY("ID");      
-- 1 +/- SELECT COUNT(*) FROM PUBLIC.ADDRESS; 
INSERT INTO "PUBLIC"."ADDRESS" VALUES
(1, 'Fairfield', 'IA', '1000 N 4th', '52556');         
CREATE MEMORY TABLE "PUBLIC"."ADMIN"(
    "ID" BIGINT DEFAULT (NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_078DFFAF_A379_4864_BBCB_0059FBF56407") NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_078DFFAF_A379_4864_BBCB_0059FBF56407",
    "CREDENTIALS_ID" BIGINT
);           
ALTER TABLE "PUBLIC"."ADMIN" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_3" PRIMARY KEY("ID");        
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.ADMIN;   
CREATE MEMORY TABLE "PUBLIC"."BRAND"(
    "ID" BIGINT DEFAULT (NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_A7569051_2908_42EC_82FF_FFCF8B6C0C5C") NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_A7569051_2908_42EC_82FF_FFCF8B6C0C5C",
    "NAME" VARCHAR(255)
);               
ALTER TABLE "PUBLIC"."BRAND" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_3C" PRIMARY KEY("ID");       
-- 9 +/- SELECT COUNT(*) FROM PUBLIC.BRAND;   
INSERT INTO "PUBLIC"."BRAND" VALUES
(1, 'Apple'),
(2, 'Beoplay'),
(3, 'Beoplay'),
(4, 'Meizu'),
(5, 'OnePlus'),
(6, 'Samsung'),
(7, 'Sony'),
(8, 'Xiaomi'),
(9, 'Other');            
CREATE MEMORY TABLE "PUBLIC"."BUYER"(
    "ID" BIGINT DEFAULT (NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_EAB85C26_B914_49E2_917A_854A20C60790") NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_EAB85C26_B914_49E2_917A_854A20C60790",
    "CREDENTIALS_ID" BIGINT,
    "SHOPPING_CART_ID" BIGINT
);           
ALTER TABLE "PUBLIC"."BUYER" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_3CA" PRIMARY KEY("ID");      
-- 1 +/- SELECT COUNT(*) FROM PUBLIC.BUYER;   
INSERT INTO "PUBLIC"."BUYER" VALUES
(1, 2, NULL);            
CREATE MEMORY TABLE "PUBLIC"."BUYER_BILLING_ADDRESSES"(
    "BUYER_ID" BIGINT NOT NULL,
    "BILLING_ADDRESSES_ID" BIGINT NOT NULL
);      
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.BUYER_BILLING_ADDRESSES; 
CREATE MEMORY TABLE "PUBLIC"."BUYER_FAVORITE_PRODUCTS"(
    "BUYER_ID" BIGINT NOT NULL,
    "FAVORITE_PRODUCTS_ID" BIGINT NOT NULL
);      
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.BUYER_FAVORITE_PRODUCTS; 
CREATE MEMORY TABLE "PUBLIC"."BUYER_SELLERS"(
    "FOLLOWERS_ID" BIGINT NOT NULL,
    "SELLERS_ID" BIGINT NOT NULL
);      
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.BUYER_SELLERS;           
CREATE MEMORY TABLE "PUBLIC"."BUYER_SHIPPING_ADDRESSES"(
    "BUYER_ID" BIGINT NOT NULL,
    "SHIPPING_ADDRESSES_ID" BIGINT NOT NULL
);    
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.BUYER_SHIPPING_ADDRESSES;
CREATE MEMORY TABLE "PUBLIC"."BUYER_ORDER"(
    "ID" BIGINT DEFAULT (NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_304EE047_2DF7_44F9_9D97_2ED60B175707") NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_304EE047_2DF7_44F9_9D97_2ED60B175707",
    "CREATE_DATE" DATE,
    "PAYMENT_METHOD" VARCHAR(255),
    "STATUS" VARCHAR(255),
    "BILLING_ADDR_ID" BIGINT,
    "BUYER_ID" BIGINT,
    "SHIPPING_ADDR_ID" BIGINT
);   
ALTER TABLE "PUBLIC"."BUYER_ORDER" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_A" PRIMARY KEY("ID");  
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.BUYER_ORDER;             
CREATE MEMORY TABLE "PUBLIC"."BUYER_ORDER_ORDER_ITEMS"(
    "BUYER_ORDER_ID" BIGINT NOT NULL,
    "ORDER_ITEMS_ID" BIGINT NOT NULL
);      
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.BUYER_ORDER_ORDER_ITEMS; 
CREATE MEMORY TABLE "PUBLIC"."CART"(
    "ID" BIGINT DEFAULT (NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_672244CE_9931_481F_806C_332D3C3C1AC7") NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_672244CE_9931_481F_806C_332D3C3C1AC7",
    "TOTAL_AMOUNT" DOUBLE,
    "BUYER_ID" BIGINT
);      
ALTER TABLE "PUBLIC"."CART" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_1" PRIMARY KEY("ID");         
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.CART;    
CREATE MEMORY TABLE "PUBLIC"."CART_CART_ITEMS"(
    "CART_ID" BIGINT NOT NULL,
    "CART_ITEMS_ID" BIGINT NOT NULL
);      
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.CART_CART_ITEMS;         
CREATE MEMORY TABLE "PUBLIC"."CART_ITEM"(
    "ID" BIGINT DEFAULT (NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_96519897_92BB_4F58_8416_2308B28154FB") NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_96519897_92BB_4F58_8416_2308B28154FB",
    "QUANTITY" INTEGER,
    "UNIT_PRICE" DOUBLE,
    "PRODUCT_ID" BIGINT
);        
ALTER TABLE "PUBLIC"."CART_ITEM" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_B" PRIMARY KEY("ID");    
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.CART_ITEM;               
CREATE MEMORY TABLE "PUBLIC"."CATEGORY"(
    "ID" BIGINT DEFAULT (NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_05CF52E9_B704_4104_906E_AC11EF5E2F2E") NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_05CF52E9_B704_4104_906E_AC11EF5E2F2E",
    "NAME" VARCHAR(255)
);            
ALTER TABLE "PUBLIC"."CATEGORY" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_31" PRIMARY KEY("ID");    
-- 9 +/- SELECT COUNT(*) FROM PUBLIC.CATEGORY;
INSERT INTO "PUBLIC"."CATEGORY" VALUES
(1, 'Computers & Laptops'),
(2, 'Cameras & Photos'),
(3, 'Hardware'),
(4, 'Smartphones & Tablets'),
(5, 'TV & Audio'),
(6, 'Gadgets'),
(7, 'Car Electronics'),
(8, 'Video Games $ Consoles'),
(9, 'Accessories');             
CREATE MEMORY TABLE "PUBLIC"."CREDENTIALS"(
    "ID" BIGINT DEFAULT (NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_64EC1097_EAD8_480E_A2D5_0176ABC70EA5") NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_64EC1097_EAD8_480E_A2D5_0176ABC70EA5",
    "EMAIL" VARCHAR(255),
    "FIRST_NAME" VARCHAR(255),
    "LAST_NAME" VARCHAR(255),
    "PASSWORD" VARCHAR(255),
    "VERIFIED" INTEGER,
    "ROLE_ID" BIGINT
);           
ALTER TABLE "PUBLIC"."CREDENTIALS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_9" PRIMARY KEY("ID");  
-- 2 +/- SELECT COUNT(*) FROM PUBLIC.CREDENTIALS;             
INSERT INTO "PUBLIC"."CREDENTIALS" VALUES
(1, 'seller@seller.com', 'Tina', 'Xing', '$2a$10$9iC/DKLxg4vlDJSmIxEbbePVekUUTrRNakyduFaocTUKWbB/mMbgq', 1, 1),
(2, 'ogabek.yuldashov@gmail.com', 'Ogabek', 'Yuldashov', '$2a$10$9iC/DKLxg4vlDJSmIxEbbePVekUUTrRNakyduFaocTUKWbB/mMbgq', 1, 2);   
CREATE MEMORY TABLE "PUBLIC"."NOTIFICATION"(
    "ID" BIGINT DEFAULT (NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_1496B911_6026_4315_9638_47A766720F5C") NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_1496B911_6026_4315_9638_47A766720F5C",
    "IS_READ" BOOLEAN,
    "MESSAGE" VARCHAR(255),
    "RECEIVER_ID" BIGINT,
    "SENDER_ID" BIGINT
);         
ALTER TABLE "PUBLIC"."NOTIFICATION" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_AD" PRIMARY KEY("ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.NOTIFICATION;            
CREATE MEMORY TABLE "PUBLIC"."ORDER_ITEM"(
    "ID" BIGINT DEFAULT (NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_7E9D1DA6_D37C_4D73_A55F_116C1EE146B9") NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_7E9D1DA6_D37C_4D73_A55F_116C1EE146B9",
    "ORDER_ITEM_STATUS" VARCHAR(255),
    "QUANTITY" INTEGER,
    "UNIT_PRICE" DOUBLE,
    "BUYER_ORDER_ID" BIGINT,
    "PRODUCT_ID" BIGINT
);  
ALTER TABLE "PUBLIC"."ORDER_ITEM" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_4" PRIMARY KEY("ID");   
-- 4 +/- SELECT COUNT(*) FROM PUBLIC.ORDER_ITEM;              
INSERT INTO "PUBLIC"."ORDER_ITEM" VALUES
(1, NULL, 1, 1.0, NULL, 1),
(2, NULL, 1, 1.0, NULL, 1),
(3, NULL, 1, 1.0, NULL, 1),
(4, NULL, 1, 1.0, NULL, 1);  
CREATE MEMORY TABLE "PUBLIC"."PRODUCT"(
    "ID" BIGINT DEFAULT (NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_55F404D9_EDBC_4FE5_9E64_7068F7D4D5C8") NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_55F404D9_EDBC_4FE5_9E64_7068F7D4D5C8",
    "DATE_PRODUCT_ADDED" DATE,
    "DESCRIPTION" VARCHAR(255),
    "DISCOUNT_RATE" DOUBLE,
    "IS_NEW_ARRIVAL" BOOLEAN,
    "NAME" VARCHAR(255),
    "OLD_PRICE" DOUBLE,
    "PRICE" DOUBLE NOT NULL,
    "PROMOTE" VARCHAR(255),
    "BRAND_ID" BIGINT,
    "CATEGORY_ID" BIGINT,
    "SELLER_ID" BIGINT
);
ALTER TABLE "PUBLIC"."PRODUCT" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_18" PRIMARY KEY("ID");     
-- 3 +/- SELECT COUNT(*) FROM PUBLIC.PRODUCT; 
INSERT INTO "PUBLIC"."PRODUCT" VALUES
(1, DATE '2019-08-13', 'Lorem Ipsum Dolor sit amet. Lorem Ipsum Dolor sit amet', 3.0, FALSE, 'HP Envy 17', 1352.0, 1299.0, NULL, 1, 1, 1),
(2, DATE '2019-08-13', 'Lorem Ipsum Dolor sit amet. Lorem Ipsum Dolor sit amet', 2.0, FALSE, 'HP Pavilion', 1732.0, 1700.0, NULL, 1, 1, 1),
(3, DATE '2019-08-13', 'Lorem Ipsum Dolor sit amet. Lorem Ipsum Dolor sit amet', 2.0, FALSE, 'HP Spectre', 1992.0, 1870.0, NULL, 1, 1, 1);    
CREATE MEMORY TABLE "PUBLIC"."PRODUCT_PRODUCT_IMGS"(
    "PRODUCT_ID" BIGINT NOT NULL,
    "PRODUCT_IMGS_ID" BIGINT NOT NULL
);            
-- 9 +/- SELECT COUNT(*) FROM PUBLIC.PRODUCT_PRODUCT_IMGS;    
INSERT INTO "PUBLIC"."PRODUCT_PRODUCT_IMGS" VALUES
(1, 1),
(1, 2),
(1, 3),
(2, 4),
(2, 5),
(2, 6),
(3, 7),
(3, 8),
(3, 9);           
CREATE MEMORY TABLE "PUBLIC"."PRODUCT_IMAGE"(
    "ID" BIGINT DEFAULT (NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_5F1507ED_2379_41D1_BBC5_8BB0C7B51F6C") NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_5F1507ED_2379_41D1_BBC5_8BB0C7B51F6C",
    "IMG_NAME" VARCHAR(255)
);   
ALTER TABLE "PUBLIC"."PRODUCT_IMAGE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_42" PRIMARY KEY("ID");               
-- 9 +/- SELECT COUNT(*) FROM PUBLIC.PRODUCT_IMAGE;           
INSERT INTO "PUBLIC"."PRODUCT_IMAGE" VALUES
(1, '9dbd7f1b-f0b8-4c8c-9f60-2d776e8e248a.jpg'),
(2, '7ce0ad2d-f0e4-44c1-b1a5-9d0836f4bb94.jpg'),
(3, '1f2b727d-5ffa-4357-a20b-ea8e843da40e.jpg'),
(4, '50f5bf4e-fd7f-42cc-ab54-154befff66c7.jpg'),
(5, '20b416b5-fb49-4bdb-9904-9a8caddc51ec.jpg'),
(6, '9dbd7f1b-f0b8-4c8c-9f60-2d776e8e248a.jpg'),
(7, '7ce0ad2d-f0e4-44c1-b1a5-9d0836f4bb94.jpg'),
(8, '1f2b727d-5ffa-4357-a20b-ea8e843da40e.jpg'),
(9, '50f5bf4e-fd7f-42cc-ab54-154befff66c7.jpg'); 
CREATE MEMORY TABLE "PUBLIC"."REVIEW"(
    "ID" BIGINT DEFAULT (NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_1AE7C9AB_17F9_4B2D_9E4B_E3EAA1ACE345") NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_1AE7C9AB_17F9_4B2D_9E4B_E3EAA1ACE345",
    "DATE_POSTED" DATE,
    "MESSAGE" VARCHAR(255),
    "STATUS" VARCHAR(255),
    "TITLE" VARCHAR(255),
    "BYR_ID" BIGINT,
    "PRODUCT_ID" BIGINT
);           
ALTER TABLE "PUBLIC"."REVIEW" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_8" PRIMARY KEY("ID");       
-- 6 +/- SELECT COUNT(*) FROM PUBLIC.REVIEW;  
INSERT INTO "PUBLIC"."REVIEW" VALUES
(1, DATE '2019-08-13', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'APPROVED', 'This is an awesome product', 1, 1),
(2, DATE '2019-08-13', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'APPROVED', 'This is an awesome product', 1, 1),
(3, DATE '2019-08-13', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'PENDING', 'This is an awesome product', 1, 2),
(4, DATE '2019-08-13', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'APPROVED', 'This is an awesome product', 1, 2),
(5, DATE '2019-08-13', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'PENDING', 'This is an awesome product', 1, 3),
(6, DATE '2019-08-13', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'APPROVED', 'This is an awesome product', 1, 3);    
CREATE MEMORY TABLE "PUBLIC"."ROLE"(
    "ID" BIGINT DEFAULT (NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_186BB2C9_03AA_4244_8F5C_A7EAFA5F07B6") NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_186BB2C9_03AA_4244_8F5C_A7EAFA5F07B6",
    "ROLE" VARCHAR(255)
);
ALTER TABLE "PUBLIC"."ROLE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_2" PRIMARY KEY("ID");         
-- 3 +/- SELECT COUNT(*) FROM PUBLIC.ROLE;    
INSERT INTO "PUBLIC"."ROLE" VALUES
(1, 'SELLER'),
(2, 'BUYER'),
(3, 'ADMIN');              
CREATE MEMORY TABLE "PUBLIC"."SELLER"(
    "ID" BIGINT DEFAULT (NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_FB0288B7_72F7_4480_88F5_85A4AFADD146") NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_FB0288B7_72F7_4480_88F5_85A4AFADD146",
    "ADDRESS_ID" BIGINT,
    "CREDENTIALS_ID" BIGINT
);
ALTER TABLE "PUBLIC"."SELLER" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_91" PRIMARY KEY("ID");      
-- 1 +/- SELECT COUNT(*) FROM PUBLIC.SELLER;  
INSERT INTO "PUBLIC"."SELLER" VALUES
(1, 1, 1);              
CREATE MEMORY TABLE "PUBLIC"."SELLER_PRODUCTS"(
    "SELLER_ID" BIGINT NOT NULL,
    "PRODUCTS_ID" BIGINT NOT NULL
);      
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.SELLER_PRODUCTS;         
ALTER TABLE "PUBLIC"."SELLER_PRODUCTS" ADD CONSTRAINT "PUBLIC"."UK_IEMJSUTF7NIMMYT7XOELAKTG1" UNIQUE("PRODUCTS_ID");          
ALTER TABLE "PUBLIC"."BUYER_ORDER_ORDER_ITEMS" ADD CONSTRAINT "PUBLIC"."UK_5JP6HW0M2LS2HX9JA2PQWU3AU" UNIQUE("ORDER_ITEMS_ID");               
ALTER TABLE "PUBLIC"."BUYER_FAVORITE_PRODUCTS" ADD CONSTRAINT "PUBLIC"."UK_HN5N079APP073YV3RIYJJ338B" UNIQUE("FAVORITE_PRODUCTS_ID");         
ALTER TABLE "PUBLIC"."BUYER_SHIPPING_ADDRESSES" ADD CONSTRAINT "PUBLIC"."UK_CR0UL3MAHCSV6T3NKJQB7XF7C" UNIQUE("SHIPPING_ADDRESSES_ID");       
ALTER TABLE "PUBLIC"."BUYER_BILLING_ADDRESSES" ADD CONSTRAINT "PUBLIC"."UK_PFTDQ8J90GI230APS61HAOJQ4" UNIQUE("BILLING_ADDRESSES_ID");         
ALTER TABLE "PUBLIC"."CART_CART_ITEMS" ADD CONSTRAINT "PUBLIC"."UK_674A9J0B3M6NNMIAHA89JHJM3" UNIQUE("CART_ITEMS_ID");        
ALTER TABLE "PUBLIC"."PRODUCT_PRODUCT_IMGS" ADD CONSTRAINT "PUBLIC"."UK_PNKHVBRR7PN0LNQWARYE71569" UNIQUE("PRODUCT_IMGS_ID"); 
ALTER TABLE "PUBLIC"."BUYER_ORDER" ADD CONSTRAINT "PUBLIC"."FKJ4UXNQOMCBPJCN44ALKEH6VAJ" FOREIGN KEY("BUYER_ID") REFERENCES "PUBLIC"."BUYER"("ID") NOCHECK;   
ALTER TABLE "PUBLIC"."BUYER_ORDER_ORDER_ITEMS" ADD CONSTRAINT "PUBLIC"."FKNSCWL62VEUJBH2YLBB2V34DM1" FOREIGN KEY("BUYER_ORDER_ID") REFERENCES "PUBLIC"."BUYER_ORDER"("ID") NOCHECK;           
ALTER TABLE "PUBLIC"."BUYER_ORDER" ADD CONSTRAINT "PUBLIC"."FKN15QFJO21UXC4WFX60WMJ4GEK" FOREIGN KEY("SHIPPING_ADDR_ID") REFERENCES "PUBLIC"."ADDRESS"("ID") NOCHECK;         
ALTER TABLE "PUBLIC"."ORDER_ITEM" ADD CONSTRAINT "PUBLIC"."FK551LOSX9J75SS5D6BFSQVIJNA" FOREIGN KEY("PRODUCT_ID") REFERENCES "PUBLIC"."PRODUCT"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."ORDER_ITEM" ADD CONSTRAINT "PUBLIC"."FK4T61HJQALCJJSY9IHDWUC1H0L" FOREIGN KEY("BUYER_ORDER_ID") REFERENCES "PUBLIC"."BUYER_ORDER"("ID") NOCHECK;        
ALTER TABLE "PUBLIC"."BUYER_ORDER_ORDER_ITEMS" ADD CONSTRAINT "PUBLIC"."FKKJGXY97JNL172X7J73QU0911K" FOREIGN KEY("ORDER_ITEMS_ID") REFERENCES "PUBLIC"."ORDER_ITEM"("ID") NOCHECK;            
ALTER TABLE "PUBLIC"."BUYER_BILLING_ADDRESSES" ADD CONSTRAINT "PUBLIC"."FK4MWBWU7ST40V3IABWLBFDQHB1" FOREIGN KEY("BILLING_ADDRESSES_ID") REFERENCES "PUBLIC"."ADDRESS"("ID") NOCHECK;         
ALTER TABLE "PUBLIC"."SELLER" ADD CONSTRAINT "PUBLIC"."FKOPT4GYYICN4AKYJ4BOSSFP10G" FOREIGN KEY("ADDRESS_ID") REFERENCES "PUBLIC"."ADDRESS"("ID") NOCHECK;    
ALTER TABLE "PUBLIC"."PRODUCT" ADD CONSTRAINT "PUBLIC"."FKESD6FY52TK7ESOO2GCLS4LFE3" FOREIGN KEY("SELLER_ID") REFERENCES "PUBLIC"."SELLER"("ID") NOCHECK;     
ALTER TABLE "PUBLIC"."CART_CART_ITEMS" ADD CONSTRAINT "PUBLIC"."FKN4WJ4T2U48QWHSP9DHUGEJS8U" FOREIGN KEY("CART_ID") REFERENCES "PUBLIC"."CART"("ID") NOCHECK; 
ALTER TABLE "PUBLIC"."CART_CART_ITEMS" ADD CONSTRAINT "PUBLIC"."FKFSG34UQHCN23TA9B4SOQHC3GC" FOREIGN KEY("CART_ITEMS_ID") REFERENCES "PUBLIC"."CART_ITEM"("ID") NOCHECK;      
ALTER TABLE "PUBLIC"."BUYER_SELLERS" ADD CONSTRAINT "PUBLIC"."FKIMPM8XDCSKXJRORLYW38ACBOV" FOREIGN KEY("SELLERS_ID") REFERENCES "PUBLIC"."SELLER"("ID") NOCHECK;              
ALTER TABLE "PUBLIC"."BUYER_FAVORITE_PRODUCTS" ADD CONSTRAINT "PUBLIC"."FKFNROUGP0GJD4EKXP6A1J1R3H4" FOREIGN KEY("FAVORITE_PRODUCTS_ID") REFERENCES "PUBLIC"."PRODUCT"("ID") NOCHECK;         
ALTER TABLE "PUBLIC"."CART" ADD CONSTRAINT "PUBLIC"."FK8LGUNGRAEPP1QQK7PXCNADONW" FOREIGN KEY("BUYER_ID") REFERENCES "PUBLIC"."BUYER"("ID") NOCHECK;          
ALTER TABLE "PUBLIC"."CART_ITEM" ADD CONSTRAINT "PUBLIC"."FKJCYD5WV4IGQNW413RGXBFU4NV" FOREIGN KEY("PRODUCT_ID") REFERENCES "PUBLIC"."PRODUCT"("ID") NOCHECK; 
ALTER TABLE "PUBLIC"."REVIEW" ADD CONSTRAINT "PUBLIC"."FKA48WW1H7HQT91BETQ5TDN1IXX" FOREIGN KEY("BYR_ID") REFERENCES "PUBLIC"."BUYER"("ID") NOCHECK;          
ALTER TABLE "PUBLIC"."SELLER_PRODUCTS" ADD CONSTRAINT "PUBLIC"."FK1LVAAGCJJUYTIDWM9608HSG0Y" FOREIGN KEY("PRODUCTS_ID") REFERENCES "PUBLIC"."PRODUCT"("ID") NOCHECK;          
ALTER TABLE "PUBLIC"."CREDENTIALS" ADD CONSTRAINT "PUBLIC"."FKK8XL3TS5X0NPY1PQ7GDGOXLEU" FOREIGN KEY("ROLE_ID") REFERENCES "PUBLIC"."ROLE"("ID") NOCHECK;     
ALTER TABLE "PUBLIC"."BUYER_SHIPPING_ADDRESSES" ADD CONSTRAINT "PUBLIC"."FKJ1SJM7F43U2HQV38BLKOFAOK4" FOREIGN KEY("SHIPPING_ADDRESSES_ID") REFERENCES "PUBLIC"."ADDRESS"("ID") NOCHECK;       
ALTER TABLE "PUBLIC"."BUYER_BILLING_ADDRESSES" ADD CONSTRAINT "PUBLIC"."FKB2IPC4CSON2K6K51YYPKQ4199" FOREIGN KEY("BUYER_ID") REFERENCES "PUBLIC"."BUYER"("ID") NOCHECK;       
ALTER TABLE "PUBLIC"."SELLER" ADD CONSTRAINT "PUBLIC"."FK8QLFIXHHSCXLBMATJEWDVJ8X3" FOREIGN KEY("CREDENTIALS_ID") REFERENCES "PUBLIC"."CREDENTIALS"("ID") NOCHECK;            
ALTER TABLE "PUBLIC"."BUYER_ORDER" ADD CONSTRAINT "PUBLIC"."FKA6503AE9KTYHB5TW9WJ63DIJ2" FOREIGN KEY("BILLING_ADDR_ID") REFERENCES "PUBLIC"."ADDRESS"("ID") NOCHECK;          
ALTER TABLE "PUBLIC"."SELLER_PRODUCTS" ADD CONSTRAINT "PUBLIC"."FKJQ1J598WVDDJ6VS3YWNDURC43" FOREIGN KEY("SELLER_ID") REFERENCES "PUBLIC"."SELLER"("ID") NOCHECK;             
ALTER TABLE "PUBLIC"."BUYER_SHIPPING_ADDRESSES" ADD CONSTRAINT "PUBLIC"."FKB8Y981JJ4ECEHDJVU2QJHYV44" FOREIGN KEY("BUYER_ID") REFERENCES "PUBLIC"."BUYER"("ID") NOCHECK;      
ALTER TABLE "PUBLIC"."BUYER_SELLERS" ADD CONSTRAINT "PUBLIC"."FK2AAY8PB5ARF8KK4LO9A2TUSBU" FOREIGN KEY("FOLLOWERS_ID") REFERENCES "PUBLIC"."BUYER"("ID") NOCHECK;             
ALTER TABLE "PUBLIC"."NOTIFICATION" ADD CONSTRAINT "PUBLIC"."FK4HTRWRUCWK0BBLWLJLQYWQ1PF" FOREIGN KEY("SENDER_ID") REFERENCES "PUBLIC"."SELLER"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."ADMIN" ADD CONSTRAINT "PUBLIC"."FKDYC6QXJQ1BBUY9BYWIAJGVHTQ" FOREIGN KEY("CREDENTIALS_ID") REFERENCES "PUBLIC"."CREDENTIALS"("ID") NOCHECK;             
ALTER TABLE "PUBLIC"."PRODUCT" ADD CONSTRAINT "PUBLIC"."FKS6CYDSUALTSRPRVLF2BB3LCAM" FOREIGN KEY("BRAND_ID") REFERENCES "PUBLIC"."BRAND"("ID") NOCHECK;       
ALTER TABLE "PUBLIC"."BUYER" ADD CONSTRAINT "PUBLIC"."FK3T6M3CDL0HH6ANFY6X2NDFYQV" FOREIGN KEY("SHOPPING_CART_ID") REFERENCES "PUBLIC"."CART"("ID") NOCHECK;  
ALTER TABLE "PUBLIC"."NOTIFICATION" ADD CONSTRAINT "PUBLIC"."FKEA58KKTOII4VFICT7KQRSQBUE" FOREIGN KEY("RECEIVER_ID") REFERENCES "PUBLIC"."BUYER"("ID") NOCHECK;               
ALTER TABLE "PUBLIC"."PRODUCT" ADD CONSTRAINT "PUBLIC"."FK1MTSBUR82FRN64DE7BALYMQ9S" FOREIGN KEY("CATEGORY_ID") REFERENCES "PUBLIC"."CATEGORY"("ID") NOCHECK; 
ALTER TABLE "PUBLIC"."BUYER_FAVORITE_PRODUCTS" ADD CONSTRAINT "PUBLIC"."FKBQHTW5QKNUUEUON6DWCIVK2VE" FOREIGN KEY("BUYER_ID") REFERENCES "PUBLIC"."BUYER"("ID") NOCHECK;       
ALTER TABLE "PUBLIC"."REVIEW" ADD CONSTRAINT "PUBLIC"."FKIYOF1SINDB9QIQR9O8NPJ8KLT" FOREIGN KEY("PRODUCT_ID") REFERENCES "PUBLIC"."PRODUCT"("ID") NOCHECK;    
ALTER TABLE "PUBLIC"."PRODUCT_PRODUCT_IMGS" ADD CONSTRAINT "PUBLIC"."FK743AYEEX1G0KGY2LIFVQ8HQ7Q" FOREIGN KEY("PRODUCT_IMGS_ID") REFERENCES "PUBLIC"."PRODUCT_IMAGE"("ID") NOCHECK;           
ALTER TABLE "PUBLIC"."PRODUCT_PRODUCT_IMGS" ADD CONSTRAINT "PUBLIC"."FKFAFSX3OE45LHBXRXBOMV8D0BN" FOREIGN KEY("PRODUCT_ID") REFERENCES "PUBLIC"."PRODUCT"("ID") NOCHECK;      
ALTER TABLE "PUBLIC"."BUYER" ADD CONSTRAINT "PUBLIC"."FK9W233BT2MWID9DX2SG3RQHSNW" FOREIGN KEY("CREDENTIALS_ID") REFERENCES "PUBLIC"."CREDENTIALS"("ID") NOCHECK;             
